# Generated by Django 2.0.1 on 2018-09-22 11:46

from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('overall_rating', models.IntegerField(choices=[(1, 'ONE STAR'), (2, 'TWO STAR'), (3, 'THREE STAR'), (4, 'FOUR STAR'), (5, 'FIVE STAR')], validators=[djchoices.choices.ChoicesValidator({1: 'ONE STAR', 2: 'TWO STAR', 3: 'THREE STAR', 4: 'FOUR STAR', 5: 'FIVE STAR'})])),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=False, verbose_name='Tick if the food item is new in the menu')),
                ('is_veg', models.BooleanField(default=False, verbose_name='Tick if the food item is vegeterian')),
                ('is_active', models.BooleanField(default=True)),
                ('order_times', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-name', '-price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_comments', models.TextField(default=None)),
                ('bill', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_list', models.ManyToManyField(related_name='order_details', to='hotel.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_value', models.IntegerField(default=0)),
                ('mobile_no', models.IntegerField(blank=True)),
                ('on_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Tick if the cart is active')),
                ('table_number', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete='PROTECT', to='hotel.MenuItem')),
            ],
        ),
        migrations.AddField(
            model_name='customerreview',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.MenuItem'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='order_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Order'),
        ),
    ]
