# Generated by Django 2.0.1 on 2018-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20180925_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
