# Generated by Django 2.0.1 on 2018-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reward_reward_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claimed_reward',
            field=models.BooleanField(default=False),
        ),
    ]
