# Generated by Django 2.0.1 on 2018-09-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20180930_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='order_ref',
        ),
    ]
