# Generated by Django 2.0.1 on 2018-09-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_customerreview_order_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='order_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Order'),
        ),
    ]
